# Generated by Django 4.1.6 on 2023-02-17 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0002_feedback_disliked_users_feedback_liked_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedbackreply',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackreply',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
