# Generated by Django 4.1.6 on 2023-02-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_disliked_users_feedback_liked_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedbackreply',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
